#!/usr/bin/env python3
"""
The one reader for the kit-generated ``workspace.yaml``.

Deliberately not PyYAML: the file is generated by ``setup.sh`` as flat
``key: value`` lines, and a migration tool that fails to start because a YAML
library is missing from someone's Python is a worse outcome than a parser that
handles exactly the file we write.

Unknown keys are dropped rather than passed through, so a typo cannot silently
become configuration. That is also why ``KNOWN_KEYS`` is here and not spread
across callers -- adding a knob means adding it in one place, and a knob absent
from this set is a knob that does nothing no matter how carefully it was
spelled in the file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

KNOWN_KEYS = (
    "play_repo",
    "spring_repo",
    "migration_root",
    "batch_size",
    "base_package",
    "kit_path",
    # Timeouts. Everything that shells out has one; the defaults live with the
    # tool that uses them, and these override.
    "mvn_timeout",          # seconds, gate.py mvn compile/test
    "java_timeout",         # seconds, gate.py signature extraction
    "dev_bash_timeout_ms",  # milliseconds, the Bash tool timeout dev must set
    "boot_timeout",         # seconds, boot.py wait-for-ready budget
    "parallel_batches",
    "run_history",
)

INT_KEYS = frozenset(
    {"batch_size", "mvn_timeout", "java_timeout", "dev_bash_timeout_ms",
     "boot_timeout", "parallel_batches"}
)


def parse_workspace_yaml(yaml_path: Path | str) -> dict[str, Any]:
    """Flat ``key: value`` reader. Missing file is an empty dict, not an error."""
    out: dict[str, Any] = {}
    yaml_path = Path(yaml_path)
    if not yaml_path.is_file():
        return out
    for line in yaml_path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or ":" not in s:
            continue
        key, _, val = s.partition(":")
        key = key.strip()
        val = val.split("#", 1)[0].strip().strip('"').strip("'")
        if key not in KNOWN_KEYS:
            continue
        if key in INT_KEYS:
            try:
                out[key] = int(val)
            except ValueError:
                continue  # a non-numeric timeout is no configuration at all
        elif val.lower() in ("true", "false"):
            out[key] = val.lower() == "true"
        else:
            out[key] = val
    return out


def find_workspace_yaml(spring_repo: Path) -> Path:
    """
    ``setup.sh`` writes workspace.yaml in the workspace dir, one level above the
    Spring repo. Falls back to a copy inside the Spring repo for hand-made
    layouts.
    """
    candidates = (
        spring_repo.parent / "workspace.yaml",
        spring_repo / "workspace.yaml",
    )
    for c in candidates:
        if c.is_file():
            return c
    return candidates[0]


def timeout(
    workspace: dict[str, Any], key: str, override: int | None, default: int
) -> int:
    """CLI flag wins, then workspace.yaml, then the tool's own default."""
    if override is not None:
        return override
    value = workspace.get(key)
    return int(value) if isinstance(value, int) and value > 0 else default
