#!/usr/bin/env bash
# Play-to-Spring Boot plugin — workspace scaffolding for a target Play repo.
# Usage: scripts/setup.sh <path-to-play-repo> [--workspace <dir>] [--spring-name <name>]
#
# Example (from kit root): ./scripts/setup.sh /path/to/your-play-repo
#   -> Creates spring-<basename>/ (sibling) and workspace.yaml.
#
# Example: ./scripts/setup.sh /path/to/your-play-repo --workspace /tmp/migrate --spring-name my-spring-app
#   -> Uses /tmp/migrate as workspace; Spring project at /tmp/migrate/my-spring-app
#
# This script only scaffolds the workspace (Spring repo skeleton,
# workspace.yaml, .migration/ state dir, route map, endpoint probes, git
# init). It does not install anything into the Play repo's .claude/ — skills
# and agents come from the installed play-to-springboot plugin itself, never
# from a per-repo copy. A copy would also shadow the plugin's own agents,
# since Claude Code lets project-level .claude/agents/ override same-named
# plugin agents.

set -e

# Kit root is parent of this script (scripts/tools/, config/ live there).
KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAY_REPO=""
WORKSPACE_DIR=""
SPRING_NAME=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      WORKSPACE_DIR="$2"
      shift 2
      ;;
    --spring-name)
      SPRING_NAME="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1"
      exit 1
      ;;
    *)
      if [[ -z "$PLAY_REPO" ]]; then
        PLAY_REPO="$1"
      fi
      shift
      ;;
  esac
done

if [[ -z "$PLAY_REPO" ]]; then
  echo "Usage: $0 <path-to-play-repo> [--workspace <dir>] [--spring-name <name>]"
  echo ""
  echo "  <path-to-play-repo>   Absolute or relative path to the Play project directory"
  echo "  --workspace <dir>     Where to create spring-* and migration state (default: parent of Play repo)"
  echo "  --spring-name <name>  Spring project directory name (default: spring-<play-repo-basename>)"
  exit 1
fi

# Resolve Play repo to absolute path
PLAY_REPO="$(cd "$PLAY_REPO" && pwd)"
PLAY_BASENAME="$(basename "$PLAY_REPO")"

# Default workspace = parent of Play repo (so spring-* is sibling of play repo)
if [[ -z "$WORKSPACE_DIR" ]]; then
  WORKSPACE_DIR="$(dirname "$PLAY_REPO")"
fi
WORKSPACE_DIR="$(mkdir -p "$WORKSPACE_DIR" && cd "$WORKSPACE_DIR" && pwd)"

# Default Spring project name = spring-<basename>
if [[ -z "$SPRING_NAME" ]]; then
  SPRING_NAME="spring-${PLAY_BASENAME}"
fi

SPRING_REPO="${WORKSPACE_DIR}/${SPRING_NAME}"

echo "Play repo:     $PLAY_REPO"
echo "Workspace:     $WORKSPACE_DIR"
echo "Spring project: $SPRING_REPO"

# Detect base Java package from Play app (first .java file)
detect_base_package() {
  local app_dir="$1"
  local f
  for f in $(find "$app_dir" -name "*.java" 2>/dev/null | head -5); do
    if [[ -f "$f" ]]; then
      local pkg=$(grep -m1 '^package ' "$f" 2>/dev/null | sed 's/package \([^;]*\);/\1/' | tr -d ' ')
      if [[ -n "$pkg" ]]; then
        # Use top-level package (first two segments) or full base for Application
        echo "$pkg"
        return
      fi
    fi
  done
  echo "com.example.application"
}

BASE_PACKAGE=$(detect_base_package "$PLAY_REPO/app" 2>/dev/null || echo "com.example.application")
echo "Base package:  $BASE_PACKAGE"

# Create Spring Boot project directory structure only — no templates.
# The builder agent (LLM) will generate pom.xml, Application.java, and application.properties
# by reading the Play project's build.sbt and application.conf for accurate dependencies and config.
echo "Creating Spring Boot project at $SPRING_REPO"
mkdir -p "$SPRING_REPO/src/main/java"
mkdir -p "$SPRING_REPO/src/main/resources"
mkdir -p "$SPRING_REPO/src/test/java"
mkdir -p "$SPRING_REPO/src/test/resources"

# Base package path
PACKAGE_PATH=$(echo "$BASE_PACKAGE" | tr '.' '/')
mkdir -p "$SPRING_REPO/src/main/java/$PACKAGE_PATH"
mkdir -p "$SPRING_REPO/src/test/java/$PACKAGE_PATH"

# workspace.yaml
WORKSPACE_YAML="${WORKSPACE_DIR}/workspace.yaml"
cat > "$WORKSPACE_YAML" << EOF
# Generated by the play-to-springboot plugin's scripts/setup.sh
play_repo: $PLAY_REPO
spring_repo: $SPRING_REPO
migration_root: $WORKSPACE_DIR
batch_size: 25
base_package: $BASE_PACKAGE
EOF
echo "Wrote $WORKSPACE_YAML"

# Progress is tracked by the migrate skill in <spring-repo>/migration-status.json.

# Agent working directory: research.md, decisions.md, QA findings, and the
# append-only dev journals that make a killed subagent resumable.
mkdir -p "${SPRING_REPO}/.migration/journal"
if [[ ! -f "${SPRING_REPO}/.gitignore" ]]; then
  echo ".migration/" > "${SPRING_REPO}/.gitignore"
fi

# Route map, populated from conf/routes rather than left as an empty stub.
# This is the baseline QA's T3 parity check compares Spring mappings against.
ROUTE_MAP="${WORKSPACE_DIR}/route-map.json"
if [[ -f "${PLAY_REPO}/conf/routes" ]]; then
  if python3 "$KIT_ROOT/scripts/tools/routes.py" \
        --routes-file "${PLAY_REPO}/conf/routes" \
        --spring-src "${SPRING_REPO}/src/main/java" > "$ROUTE_MAP" 2>/dev/null; then
    route_count=$(python3 -c "import json;print(len(json.load(open('$ROUTE_MAP'))['play_routes']))" 2>/dev/null || echo "?")
    echo "Wrote $ROUTE_MAP ($route_count Play routes)"
  else
    echo '{"play_routes":[],"spring_endpoints":[]}' > "$ROUTE_MAP"
    echo "Could not parse conf/routes; wrote empty $ROUTE_MAP" >&2
  fi
elif [[ ! -f "$ROUTE_MAP" ]]; then
  echo '{"play_routes":[],"spring_endpoints":[]}' > "$ROUTE_MAP"
  echo "No conf/routes found; created empty $ROUTE_MAP"
fi

# T5 probe list. Never overwritten: QA fills in path_params and enables mutating
# verbs by hand, and a re-run of setup must not throw that work away.
PROBES="${SPRING_REPO}/.migration/endpoint-probes.json"
if [[ -f "${PLAY_REPO}/conf/routes" ]] && [[ ! -f "$PROBES" ]]; then
  if python3 "$KIT_ROOT/scripts/tools/endpoint_diff.py" probes \
        --routes "${PLAY_REPO}/conf/routes" --out "$PROBES" 2>/dev/null; then
    probe_count=$(python3 -c "import json;print(sum(1 for p in json.load(open('$PROBES'))['probes'] if p['enabled']))" 2>/dev/null || echo "?")
    echo "Wrote $PROBES ($probe_count enabled by default; the rest need a sample value or a body)"
  fi
fi

# The Spring project needs to be a git repo so the manager can commit after each
# layer passes QA -- that is what gives a rejected review gate something to reset
# to, instead of a manual unwind.
MIGRATION_BRANCH="migration/${PLAY_BASENAME}"
if [[ ! -d "${SPRING_REPO}/.git" ]]; then
  git -C "$SPRING_REPO" init -q
  git -C "$SPRING_REPO" checkout -q -b "$MIGRATION_BRANCH" 2>/dev/null || true
  echo "Initialized git in $SPRING_REPO on branch $MIGRATION_BRANCH"
else
  current=$(git -C "$SPRING_REPO" branch --show-current 2>/dev/null || echo "")
  echo "Spring repo already under git (branch: ${current:-detached})"
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Workspace:      $WORKSPACE_DIR"
echo "  Play repo:      $PLAY_REPO  (READ-ONLY during migration)"
echo "  Spring project: $SPRING_REPO"
echo "  Agent state:    $SPRING_REPO/migration-status.json (created by /play-to-springboot:migrate)"
echo "  Agent scratch:  $SPRING_REPO/.migration/ (research, decisions, findings, journals)"
echo ""
echo "Next: run /play-to-springboot:migrate $PLAY_REPO"
echo ""
echo "Deterministic helpers (run these yourself any time):"
echo "  python3 $KIT_ROOT/scripts/tools/inventory.py --play-repo $PLAY_REPO"
echo "  python3 $KIT_ROOT/scripts/tools/verify.py --play-repo $PLAY_REPO --spring-repo $SPRING_REPO"
echo "  python3 $KIT_ROOT/scripts/tools/gate.py --play-repo $PLAY_REPO --spring-repo $SPRING_REPO --layer service --jar <jar>"
echo ""
