#!/usr/bin/env bash
# Play-to-Spring Migration Kit — one-time setup for any Play Framework repo.
# Usage: scripts/setup.sh <path-to-play-repo> [--workspace <dir>] [--spring-name <name>]
#
# Example (from kit root): ./scripts/setup.sh /path/to/your-play-repo
#   -> Creates spring-<basename>/ (sibling), workspace.yaml, <play-repo>/.cursor/{config,docs,skills} (Cursor-native layout).
#
# Example: ./scripts/setup.sh /path/to/your-play-repo --workspace /tmp/migrate --spring-name my-spring-app
#   -> Uses /tmp/migrate as workspace; Spring project at /tmp/migrate/my-spring-app

set -e

# Kit root is parent of this script (lib/, skills/, config/ live there).
KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAY_REPO=""
WORKSPACE_DIR=""
SPRING_NAME=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      WORKSPACE_DIR="$2"
      shift 2
      ;;
    --spring-name)
      SPRING_NAME="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1"
      exit 1
      ;;
    *)
      if [[ -z "$PLAY_REPO" ]]; then
        PLAY_REPO="$1"
      fi
      shift
      ;;
  esac
done

if [[ -z "$PLAY_REPO" ]]; then
  echo "Usage: $0 <path-to-play-repo> [--workspace <dir>] [--spring-name <name>]"
  echo ""
  echo "  <path-to-play-repo>   Absolute or relative path to the Play project directory"
  echo "  --workspace <dir>     Where to create spring-* and migration state (default: parent of Play repo)"
  echo "  --spring-name <name>  Spring project directory name (default: spring-<play-repo-basename>)"
  exit 1
fi

# Resolve Play repo to absolute path
PLAY_REPO="$(cd "$PLAY_REPO" && pwd)"
PLAY_BASENAME="$(basename "$PLAY_REPO")"

# Default workspace = parent of Play repo (so spring-* is sibling of play repo)
if [[ -z "$WORKSPACE_DIR" ]]; then
  WORKSPACE_DIR="$(dirname "$PLAY_REPO")"
fi
WORKSPACE_DIR="$(mkdir -p "$WORKSPACE_DIR" && cd "$WORKSPACE_DIR" && pwd)"

# Default Spring project name = spring-<basename>
if [[ -z "$SPRING_NAME" ]]; then
  SPRING_NAME="spring-${PLAY_BASENAME}"
fi

SPRING_REPO="${WORKSPACE_DIR}/${SPRING_NAME}"

echo "Play repo:     $PLAY_REPO"
echo "Workspace:     $WORKSPACE_DIR"
echo "Spring project: $SPRING_REPO"

# Detect base Java package from Play app (first .java file)
detect_base_package() {
  local app_dir="$1"
  local f
  for f in $(find "$app_dir" -name "*.java" 2>/dev/null | head -5); do
    if [[ -f "$f" ]]; then
      local pkg=$(grep -m1 '^package ' "$f" 2>/dev/null | sed 's/package \([^;]*\);/\1/' | tr -d ' ')
      if [[ -n "$pkg" ]]; then
        # Use top-level package (first two segments) or full base for Application
        echo "$pkg"
        return
      fi
    fi
  done
  echo "com.example.application"
}

BASE_PACKAGE=$(detect_base_package "$PLAY_REPO/app" 2>/dev/null || echo "com.example.application")
echo "Base package:  $BASE_PACKAGE"

# Kit reference lives under <play-repo>/.cursor/ for both editors to read.
# Copy in place rather than rm -rf: this script runs on every orchestrator
# invocation, and wiping the directory destroys notes the user added here.
KIT_DEST="${PLAY_REPO}/.cursor"
echo "Installing kit reference under $KIT_DEST (config/, docs/)"
mkdir -p "$KIT_DEST"
cp -r "$KIT_ROOT/config" "$KIT_DEST/"
if [[ -d "$KIT_ROOT/docs" ]]; then
  cp -r "$KIT_ROOT/docs" "$KIT_DEST/"
fi

# Copy dev-toolkit JAR from kit lib/ to the base directory of the source Play project
# Path after setup: <play-repo>/dev-toolkit-1.0.0.jar
if [[ -d "$KIT_ROOT/lib" ]]; then
  count=0
  for jar in "$KIT_ROOT/lib"/*.jar; do
    [[ -f "$jar" ]] || continue
    cp "$jar" "$PLAY_REPO/"
    echo "  $(basename "$jar") -> $PLAY_REPO/"
    count=$((count + 1))
  done
  if [[ $count -gt 0 ]]; then
    echo "Copied $count JAR(s) to $PLAY_REPO/ (run: java -jar dev-toolkit-1.0.0.jar migrate-app)"
  fi
else
  echo "No kit lib/ found at $KIT_ROOT/lib (add dev-toolkit-1.0.0.jar for deterministic transform)"
fi

# Create Spring Boot project directory structure only — no templates.
# The builder agent (LLM) will generate pom.xml, Application.java, and application.properties
# by reading the Play project's build.sbt and application.conf for accurate dependencies and config.
echo "Creating Spring Boot project at $SPRING_REPO"
mkdir -p "$SPRING_REPO/src/main/java"
mkdir -p "$SPRING_REPO/src/main/resources"
mkdir -p "$SPRING_REPO/src/test/java"
mkdir -p "$SPRING_REPO/src/test/resources"

# Base package path
PACKAGE_PATH=$(echo "$BASE_PACKAGE" | tr '.' '/')
mkdir -p "$SPRING_REPO/src/main/java/$PACKAGE_PATH"
mkdir -p "$SPRING_REPO/src/test/java/$PACKAGE_PATH"

# workspace.yaml
WORKSPACE_YAML="${WORKSPACE_DIR}/workspace.yaml"
cat > "$WORKSPACE_YAML" << EOF
# Generated by play-to-spring-kit scripts/setup.sh
play_repo: $PLAY_REPO
spring_repo: $SPRING_REPO
migration_root: $WORKSPACE_DIR
batch_size: 25
base_package: $BASE_PACKAGE
kit_path: $KIT_DEST
EOF
echo "Wrote $WORKSPACE_YAML"

# Progress is tracked by the manager in <spring-repo>/migration-status.json.

# Agent working directory: research.md, decisions.md, QA findings, and the
# append-only dev journals that make a killed subagent resumable.
mkdir -p "${SPRING_REPO}/.migration/journal"
if [[ ! -f "${SPRING_REPO}/.gitignore" ]]; then
  echo ".migration/" > "${SPRING_REPO}/.gitignore"
fi

# Route map, populated from conf/routes rather than left as an empty stub.
# This is the baseline QA's T3 parity check compares Spring mappings against.
ROUTE_MAP="${WORKSPACE_DIR}/route-map.json"
if [[ -f "${PLAY_REPO}/conf/routes" ]]; then
  if python3 "$KIT_ROOT/scripts/tools/routes.py" \
        --routes-file "${PLAY_REPO}/conf/routes" \
        --spring-src "${SPRING_REPO}/src/main/java" > "$ROUTE_MAP" 2>/dev/null; then
    route_count=$(python3 -c "import json;print(len(json.load(open('$ROUTE_MAP'))['play_routes']))" 2>/dev/null || echo "?")
    echo "Wrote $ROUTE_MAP ($route_count Play routes)"
  else
    echo '{"play_routes":[],"spring_endpoints":[]}' > "$ROUTE_MAP"
    echo "Could not parse conf/routes; wrote empty $ROUTE_MAP" >&2
  fi
elif [[ ! -f "$ROUTE_MAP" ]]; then
  echo '{"play_routes":[],"spring_endpoints":[]}' > "$ROUTE_MAP"
  echo "No conf/routes found; created empty $ROUTE_MAP"
fi

# T5 probe list. Never overwritten: QA fills in path_params and enables mutating
# verbs by hand, and a re-run of setup must not throw that work away.
PROBES="${SPRING_REPO}/.migration/endpoint-probes.json"
if [[ -f "${PLAY_REPO}/conf/routes" ]] && [[ ! -f "$PROBES" ]]; then
  if python3 "$KIT_ROOT/scripts/tools/endpoint_diff.py" probes \
        --routes "${PLAY_REPO}/conf/routes" --out "$PROBES" 2>/dev/null; then
    probe_count=$(python3 -c "import json;print(sum(1 for p in json.load(open('$PROBES'))['probes'] if p['enabled']))" 2>/dev/null || echo "?")
    echo "Wrote $PROBES ($probe_count enabled by default; the rest need a sample value or a body)"
  fi
fi

# The Spring project needs to be a git repo so the manager can commit after each
# layer passes QA -- that is what gives a rejected review gate something to reset
# to, instead of a manual unwind.
MIGRATION_BRANCH="migration/${PLAY_BASENAME}"
if [[ ! -d "${SPRING_REPO}/.git" ]]; then
  git -C "$SPRING_REPO" init -q
  git -C "$SPRING_REPO" checkout -q -b "$MIGRATION_BRANCH" 2>/dev/null || true
  echo "Initialized git in $SPRING_REPO on branch $MIGRATION_BRANCH"
else
  current=$(git -C "$SPRING_REPO" branch --show-current 2>/dev/null || echo "")
  echo "Spring repo already under git (branch: ${current:-detached})"
fi

# Install skills for both editors: <play-repo>/.claude/skills/<name>/SKILL.md and
# the same content under .cursor/skills/.
#
# The source files in kit skills/ already carry valid YAML frontmatter, so they
# are copied through verbatim. The previous version emitted its own
# ---name/description--- header and then cat'd a file that started with its own
# ---, producing two frontmatter blocks in every installed SKILL.md.
CLAUDE_SKILLS_ROOT="${PLAY_REPO}/.claude/skills"
CURSOR_SKILLS_ROOT="${PLAY_REPO}/.cursor/skills"
echo "Installing agent skills"
mkdir -p "$CLAUDE_SKILLS_ROOT" "$CURSOR_SKILLS_ROOT"

for skill_md in "$KIT_ROOT/skills"/*.md; do
  [[ -f "$skill_md" ]] || continue
  base=$(basename "$skill_md" .md)
  if [[ "$base" == play-spring-* ]]; then
    name="$base"
  else
    name="play-spring-${base%-skill}"   # legacy: transformer-skill -> play-spring-transformer
  fi
  if ! head -1 "$skill_md" | grep -q '^---$'; then
    echo "  WARNING: $base has no frontmatter; skipping" >&2
    continue
  fi
  for root in "$CLAUDE_SKILLS_ROOT" "$CURSOR_SKILLS_ROOT"; do
    mkdir -p "${root}/${name}"
    cp "$skill_md" "${root}/${name}/SKILL.md"
  done
  echo "  $name"
done

# Claude Code subagent definitions. These carry the tool grants that make role
# boundaries mechanical rather than advisory: only play-spring-dev gets Edit and
# Write. Cursor has no subagent isolation, so it gets the skills only -- see
# docs/STATE-CONTRACT.md for what that path gives up.
if [[ -d "$KIT_ROOT/agents" ]]; then
  CLAUDE_AGENTS_ROOT="${PLAY_REPO}/.claude/agents"
  echo "Installing Claude Code subagents into $CLAUDE_AGENTS_ROOT"
  mkdir -p "$CLAUDE_AGENTS_ROOT"
  for agent_md in "$KIT_ROOT/agents"/*.md; do
    [[ -f "$agent_md" ]] || continue
    cp "$agent_md" "$CLAUDE_AGENTS_ROOT/"
    echo "  $(basename "$agent_md" .md)"
  done
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Workspace:      $WORKSPACE_DIR"
echo "  Play repo:      $PLAY_REPO  (READ-ONLY during migration)"
echo "  Spring project: $SPRING_REPO"
echo "  Kit reference:  $KIT_DEST (config/, docs/)"
echo "  Agent state:    $SPRING_REPO/migration-status.json (created by the manager)"
echo "  Agent scratch:  $SPRING_REPO/.migration/ (research, decisions, findings, journals)"
echo ""
echo "Claude Code:  $PLAY_REPO/.claude/skills/ + .claude/agents/   <- role isolation enforced"
echo "Cursor:       $PLAY_REPO/.cursor/skills/                     <- skills only, no subagents"
if [[ -d "$KIT_ROOT/lib" ]] && [[ -n "$(find "$KIT_ROOT/lib" -maxdepth 1 -name '*.jar' 2>/dev/null)" ]]; then
  echo "dev-toolkit JAR copied to: $PLAY_REPO/dev-toolkit-1.0.0.jar"
fi
echo ""
echo "Next steps:"
echo "  1. Open $PLAY_REPO in Claude Code."
echo "  2. Invoke the play-spring-manager skill:"
echo "       \"Run the play-spring-manager skill for this workspace; resume from"
echo "        migration-status.json if present.\""
echo "  3. The manager stops at Gate 1 with the architect's decisions for your review."
echo ""
echo "Deterministic helpers (run these yourself any time):"
echo "  python3 $KIT_ROOT/scripts/tools/inventory.py --play-repo $PLAY_REPO"
echo "  python3 $KIT_ROOT/scripts/tools/verify.py --play-repo $PLAY_REPO --spring-repo $SPRING_REPO"
echo "  python3 $KIT_ROOT/scripts/tools/gate.py --play-repo $PLAY_REPO --spring-repo $SPRING_REPO --layer service"
echo ""
