#!/usr/bin/env bash
# Play-to-Spring Migration Kit — one-time setup for any Play Framework repo.
# Usage: scripts/setup.sh <path-to-play-repo> [--workspace <dir>] [--spring-name <name>]
#
# Example (from kit root): ./scripts/setup.sh /path/to/your-play-repo
#   -> Creates spring-<basename>/ (sibling), workspace.yaml, <play-repo>/.cursor/{config,docs,skills} (Cursor-native layout).
#
# Example: ./scripts/setup.sh /path/to/your-play-repo --workspace /tmp/migrate --spring-name my-spring-app
#   -> Uses /tmp/migrate as workspace; Spring project at /tmp/migrate/my-spring-app

set -e

# Kit root is parent of this script (lib/, skills/, config/ live there).
KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAY_REPO=""
WORKSPACE_DIR=""
SPRING_NAME=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      WORKSPACE_DIR="$2"
      shift 2
      ;;
    --spring-name)
      SPRING_NAME="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1"
      exit 1
      ;;
    *)
      if [[ -z "$PLAY_REPO" ]]; then
        PLAY_REPO="$1"
      fi
      shift
      ;;
  esac
done

if [[ -z "$PLAY_REPO" ]]; then
  echo "Usage: $0 <path-to-play-repo> [--workspace <dir>] [--spring-name <name>]"
  echo ""
  echo "  <path-to-play-repo>   Absolute or relative path to the Play project directory"
  echo "  --workspace <dir>     Where to create spring-* and migration state (default: parent of Play repo)"
  echo "  --spring-name <name>  Spring project directory name (default: spring-<play-repo-basename>)"
  exit 1
fi

# Resolve Play repo to absolute path
PLAY_REPO="$(cd "$PLAY_REPO" && pwd)"
PLAY_BASENAME="$(basename "$PLAY_REPO")"

# Default workspace = parent of Play repo (so spring-* is sibling of play repo)
if [[ -z "$WORKSPACE_DIR" ]]; then
  WORKSPACE_DIR="$(dirname "$PLAY_REPO")"
fi
WORKSPACE_DIR="$(mkdir -p "$WORKSPACE_DIR" && cd "$WORKSPACE_DIR" && pwd)"

# Default Spring project name = spring-<basename>
if [[ -z "$SPRING_NAME" ]]; then
  SPRING_NAME="spring-${PLAY_BASENAME}"
fi

SPRING_REPO="${WORKSPACE_DIR}/${SPRING_NAME}"

echo "Play repo:     $PLAY_REPO"
echo "Workspace:     $WORKSPACE_DIR"
echo "Spring project: $SPRING_REPO"

# Detect base Java package from Play app (first .java file)
detect_base_package() {
  local app_dir="$1"
  local f
  for f in $(find "$app_dir" -name "*.java" 2>/dev/null | head -5); do
    if [[ -f "$f" ]]; then
      local pkg=$(grep -m1 '^package ' "$f" 2>/dev/null | sed 's/package \([^;]*\);/\1/' | tr -d ' ')
      if [[ -n "$pkg" ]]; then
        # Use top-level package (first two segments) or full base for Application
        echo "$pkg"
        return
      fi
    fi
  done
  echo "com.example.application"
}

BASE_PACKAGE=$(detect_base_package "$PLAY_REPO/app" 2>/dev/null || echo "com.example.application")
echo "Base package:  $BASE_PACKAGE"

# Cursor uses <play-repo>/.cursor/ — keep everything there: skills/ (Agent) + config/ + docs/ reference.
# Do not copy raw kit skills/*.md into .cursor/skills/; those paths are reserved for play-spring-*/SKILL.md below.
KIT_DEST="${PLAY_REPO}/.cursor"
echo "Installing kit reference under $KIT_DEST (config/, docs/)"
mkdir -p "$KIT_DEST"
rm -rf "$KIT_DEST/config" "$KIT_DEST/docs"
cp -r "$KIT_ROOT/config" "$KIT_DEST/"
if [[ -d "$KIT_ROOT/docs" ]]; then
  cp -r "$KIT_ROOT/docs" "$KIT_DEST/"
fi

# Copy dev-toolkit JAR from kit lib/ to the base directory of the source Play project
# Path after setup: <play-repo>/dev-toolkit-1.0.0.jar
if [[ -d "$KIT_ROOT/lib" ]]; then
  count=0
  for jar in "$KIT_ROOT/lib"/*.jar; do
    [[ -f "$jar" ]] || continue
    cp "$jar" "$PLAY_REPO/"
    echo "  $(basename "$jar") -> $PLAY_REPO/"
    count=$((count + 1))
  done
  if [[ $count -gt 0 ]]; then
    echo "Copied $count JAR(s) to $PLAY_REPO/ (run: java -jar dev-toolkit-1.0.0.jar migrate-app)"
  fi
else
  echo "No kit lib/ found at $KIT_ROOT/lib (add dev-toolkit-1.0.0.jar for deterministic transform)"
fi

# Create Spring Boot project directory structure only — no templates.
# The builder agent (LLM) will generate pom.xml, Application.java, and application.properties
# by reading the Play project's build.sbt and application.conf for accurate dependencies and config.
echo "Creating Spring Boot project at $SPRING_REPO"
mkdir -p "$SPRING_REPO/src/main/java"
mkdir -p "$SPRING_REPO/src/main/resources"
mkdir -p "$SPRING_REPO/src/test/java"
mkdir -p "$SPRING_REPO/src/test/resources"

# Base package path
PACKAGE_PATH=$(echo "$BASE_PACKAGE" | tr '.' '/')
mkdir -p "$SPRING_REPO/src/main/java/$PACKAGE_PATH"
mkdir -p "$SPRING_REPO/src/test/java/$PACKAGE_PATH"

# workspace.yaml
WORKSPACE_YAML="${WORKSPACE_DIR}/workspace.yaml"
cat > "$WORKSPACE_YAML" << EOF
# Generated by play-to-spring-kit scripts/setup.sh
play_repo: $PLAY_REPO
spring_repo: $SPRING_REPO
migration_root: $WORKSPACE_DIR
batch_size: 25
base_package: $BASE_PACKAGE
kit_path: $KIT_DEST
EOF
echo "Wrote $WORKSPACE_YAML"

# Progress is tracked by the orchestrator in <spring-repo>/migration-status.json (created on first agent run).

# Optional placeholder route-map (no tooling required)
ROUTE_MAP="${WORKSPACE_DIR}/route-map.json"
if [[ ! -f "$ROUTE_MAP" ]]; then
  echo '{"play_routes":[],"spring_endpoints":[]}' > "$ROUTE_MAP"
  echo "Created $ROUTE_MAP"
fi

# Copy skills into Play (source) repo in Cursor Agent format: .cursor/skills/<skill-name>/SKILL.md
# So when the customer opens the Play repo in Cursor, the agent discovers these skills.
CURSOR_SKILLS_ROOT="${PLAY_REPO}/.cursor/skills"
echo "Installing Cursor Agent skills into $CURSOR_SKILLS_ROOT"
mkdir -p "$CURSOR_SKILLS_ROOT"

skill_descriptions() {
  case "$1" in
    transformer-skill) echo "Transform Play Framework Java files to Spring Boot. Use when migrating controllers, services, or any Play class." ;;
    builder-skill)     echo "Compile Spring project and fix errors until build passes. Use after transforming files." ;;
    orchestrator-skill) echo "Run the full migration: Transform (CLI) then Validation (compile + fix until clean)." ;;
    *)                echo "Play-to-Spring migration skill." ;;
  esac
}

for skill_md in "$KIT_ROOT/skills"/*.md; do
  [[ -f "$skill_md" ]] || continue
  base=$(basename "$skill_md" .md)
  # skill name: transformer-skill -> play-spring-transformer (Cursor: lowercase, hyphens)
  name="play-spring-${base%-skill}"
  desc=$(skill_descriptions "$base")
  skill_dir="${CURSOR_SKILLS_ROOT}/${name}"
  mkdir -p "$skill_dir"
  {
    echo "---"
    echo "name: $name"
    echo "description: $desc"
    echo "---"
    echo ""
    cat "$skill_md"
  } > "$skill_dir/SKILL.md"
  echo "  $name"
done

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Workspace:       $WORKSPACE_DIR"
echo "  Play repo:      $PLAY_REPO"
echo "  Spring project: $SPRING_REPO"
echo "  Cursor / kit:     $KIT_DEST (skills/ + config/ + docs/)"
echo "  Agent state:    $SPRING_REPO/migration-status.json (created by orchestrator)"
echo ""
echo "Cursor Agent skills: $PLAY_REPO/.cursor/skills/"
echo "  (Open the Play repo or workspace in Cursor; Agent will discover play-spring-* skills.)"
if [[ -d "$KIT_ROOT/lib" ]] && [[ -n "$(find "$KIT_ROOT/lib" -maxdepth 1 -name '*.jar' 2>/dev/null)" ]]; then
  echo "dev-toolkit JAR copied to: $PLAY_REPO/dev-toolkit-1.0.0.jar"
  echo "  (From Play repo: java -jar dev-toolkit-1.0.0.jar migrate-app)"
fi
echo ""
echo "Next steps:"
echo "  1. Open $WORKSPACE_DIR (or $PLAY_REPO) in Cursor so Agent sees .cursor/skills/"
echo "  2. Autonomous run: Cursor Agent + skill play-spring-orchestrator + one-liner (see docs/play_to_spring_migration.md §2.1)."
echo "  3. Manual CLI only: cd $PLAY_REPO && java -jar dev-toolkit-1.0.0.jar migrate-app"
echo "  4. Spring build: cd $SPRING_REPO && mvn compile"
echo ""
